
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  labels:
    app: getting-started
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
      - name: getting-started
        image: docker/getting-started
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
  labels:
    app: getting-started
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: getting-started

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: getting-started-ingress
  namespace: default
  labels:
    app: getting-started
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
spec:
  rules:
    - host: tty.com
      http:
        paths:
          - backend:
              serviceName: getting-started-service
              servicePort: 80
            path: /
